const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {JSDOM}=require('jsdom');
const sample={date:'2026-09-13',no:'020',league:'法甲',home:'布雷斯特',away:'巴黎圣曼',kickoff:'2026-09-13T18:45:00Z',mode:'SINGLE',direction:'客胜',verified:true,result:'A',coverageHit:true,top1Hit:true,handicap:'让胜',handicapHit:false,frozenAt:'2026-09-13T15:42:01Z',pregameVerified:true,version:'3.2'};
const flush=()=>new Promise(r=>setTimeout(r,25));
async function setup(route='home',fetcher=async()=>({ok:true,json:async()=>({ok:true,rows:[]})})){
 const dom=new JSDOM(fs.readFileSync('client-v1.html','utf8'),{url:'https://hjh19970220.github.io/client-v1.html#/'+route,runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.scrollTo=()=>{};w.fetch=fetcher;w.AbortController=AbortController;w.SorenAuth={callback:async()=>false,user:async()=>null,checkout:async()=>{throw Error('PRO 尚未开放购买，目前不会产生费用。')}};w.eval(fs.readFileSync('assets/soren/data.js','utf8'));w.eval(fs.readFileSync('assets/soren/app.js','utf8'));await flush();return dom;
}
test('today sends Shanghai date and never presents stale rows as today',async()=>{let url;const d=await setup('home',async u=>{url=u;return {ok:true,json:async()=>({ok:true,rows:[sample]})}});assert.match(url,/client=1&view=today&date=/);assert.match(d.window.document.body.textContent,/今日赛事尚未发布/);assert.doesNotMatch(d.window.document.body.textContent,/布雷斯特/);d.window.close();});
test('HTTP failure displays retry and navigation remains usable',async()=>{const d=await setup('matches',async()=>({ok:false}));const doc=d.window.document;assert.match(doc.body.textContent,/连接暂时中断/);assert.ok(doc.querySelector('[data-action="retry-today"]'));d.window.location.hash='#/user';await flush();assert.match(doc.body.textContent,/你好，球迷/);d.window.close();});
test('history reads production settlements, version filter and separate metrics',async()=>{const d=await setup('history',async()=>({ok:true,json:async()=>({ok:true,rows:[sample]})}));let doc=d.window.document;assert.match(doc.querySelector('.stats').textContent,/100.0%/);doc.querySelector('[data-stat="handicap"]').click();assert.match(doc.querySelector('.stats').textContent,/0.0%/);doc.querySelector('[data-version="3.3"]').click();assert.match(doc.body.textContent,/等待可核验的记录/);assert.doesNotMatch(doc.querySelector('.stats').textContent,/0.0%/);d.window.close();});
test('detail, favorites and reload-safe deep link',async()=>{const id=encodeURIComponent([sample.date,sample.no,sample.home,sample.away].join('|'));const d=await setup('detail/'+id,async()=>({ok:true,json:async()=>({ok:true,rows:[sample]})}));const doc=d.window.document;assert.match(doc.body.textContent,/客胜/);assert.match(doc.body.textContent,/分析依据/);doc.querySelector('[data-favorite]').click();assert.match(doc.body.textContent,/已收藏/);assert.ok(d.window.localStorage.getItem('soren-favorites').includes(id));doc.querySelector('[data-favorite]').click();assert.equal(d.window.localStorage.getItem('soren-favorites'),'[]');d.window.close();});
test('HTML injection in team name is escaped',async()=>{const d=await setup('history',async()=>({ok:true,json:async()=>({ok:true,rows:[{...sample,home:'<img src=x onerror=alert(1)>'}]})}));assert.equal(d.window.document.querySelectorAll('img[onerror]').length,0);assert.match(d.window.document.body.textContent,/<img src=x/);d.window.close();});
test('malformed data shows error instead of fabricated zero results',async()=>{const d=await setup('history',async()=>({ok:true,json:async()=>({ok:true,rows:{}})}));assert.match(d.window.document.body.textContent,/连接暂时中断/);d.window.close();});
test('in-flight response does not erase a login form after navigation',async()=>{let resolve;const d=await setup('matches',()=>new Promise(r=>{resolve=r}));d.window.location.hash='#/login';await flush();d.window.document.querySelector('#email').value='test@example.invalid';resolve({ok:true,json:async()=>({ok:true,rows:[]})});await flush();assert.equal(d.window.document.querySelector('#email').value,'test@example.invalid');d.window.close();});
test('empty collection and PRO unavailable states are actionable',async()=>{const d=await setup('favorites');assert.match(d.window.document.body.textContent,/还没有收藏比赛/);d.window.location.hash='#/membership';await flush();d.window.document.querySelector('[data-action="checkout"]').click();await flush();assert.match(d.window.document.querySelector('#toast').textContent,/不会产生费用/);d.window.close();});
